kind: pipeline
type: docker
name: hello-world

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: say-hello
    image: debian:buster
    commands:
      - echo hello-world

# Pipeline steps are defined as a series of shell commands. 
# - The commands are executed inside the root directory of your git repository. 
# - The root of your git repository, also called the workspace, is shared by all steps in your pipeline.

# The 'commands' are executed inside the root directory of your git repository
# The 'environment' section provides the ability to define environment variables scoped to individual pipeline steps.
# Host mounts allow you to mount an absolute path on the host machine into a pipeline step.

# The first step is to define the host machine volume path. The host volume path must be an absolute path.
# volumes:
# - name: cache
#   host:
#     path: /var/lib/cache

# The next step is to configure your pipeline step to mount the named host path into your container. 
# The container path must also be an absolute path.

# steps:
# - name: build
#   image: node
#   volumes:
#   - name: cache
#     path: /tmp/cache